# Site settings
title: Arth Tyagi
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arth Tyagi
user_description: I like working on stuff that intrigue me. I founded a startup to build open-source ML applications last year. Right now, I am a high school senior, developer, blogger and occasionally composing music for fun. I'm a contributing and voting member of the Python Software Foundation. As of now, I'm working on Tor Project's open-source repositories including Nyx and Stem both of which are written with Python as the core language. I am developing my own Tor Client in Python and also an improved open-source tool similar to Nyx for monitoring Tor connections with a beautiful GUI as a localhost web application. I'm also planning on building an ed-tech platform with Django as the core technology to help people to learn code.
user_title: Full Stack Developer. ML Hobbyist.
email: ceo@arisveam.com
twitter_username: arthtyagi
github_username:  arthtyagi

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
